# Generated by Django 5.2.5 on 2025-08-31 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Atividade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descricao", models.CharField(max_length=500)),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("urgente", "Urgente"),
                            ("importante", "Importante"),
                            ("precisa ser feita", "Precisa ser feita"),
                        ],
                        default="importante",
                        max_length=100,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("concluida", "Concluída"),
                            ("pendente", "Pendente"),
                            ("adiada", "Adiada"),
                        ],
                        default="pendente",
                        max_length=50,
                    ),
                ),
            ],
        ),
    ]
