# Generated by Django 5.2.5 on 2025-08-31 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("atividades", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="atividade",
            name="titulo",
        ),
    ]
