# Generated by Django 5.2.5 on 2025-08-31 14:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atividades", "0002_remove_atividade_titulo"),
    ]

    operations = [
        migrations.AddField(
            model_name="atividade",
            name="data_vencimento",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
